version: '2'
services:
 php:
   image: minha_imagem
   ports:
     - "8080:80"
   links: 
     - db  
 
 db:
   image: mysql:5.7
   volumes:
    - /home/rafael/Downloads/vol_mysql:/var/lib/mysql
   environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=loja
    - MYSQL_USER=root
    - MYSQL_ROOT_HOST=0.0.0.0
